name: easy_software
description: A Flutter package that contains a collection of widgets for the rapid development of custom software, such as CRMs, ERPs, and others..
version: 0.1.0
homepage: https://github.com/bran-x/easy_software

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0